-- Part 3: Tables and Views

CREATE TABLE public.badges (
    id character varying NOT NULL,
    name character varying NOT NULL,
    description text,
    icon_name character varying,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.beta_signups (
    id bigint NOT NULL,
    email character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    user_id uuid
);

ALTER TABLE public.beta_signups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.beta_signups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.cafe_analytics (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    cafe_id bigint NOT NULL,
    event_type character varying NOT NULL,
    profile_id uuid
);

ALTER TABLE public.cafe_analytics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cafe_analytics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.cafe_reviews (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    cafe_id bigint NOT NULL,
    profile_id uuid NOT NULL,
    rating integer NOT NULL,
    comment text,
    CONSTRAINT cafe_reviews_rating_check CHECK (((rating >= 1) AND (rating <= 5)))
);

ALTER TABLE public.cafe_reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cafe_reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.cafes (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name character varying NOT NULL,
    address character varying,
    city character varying,
    gmaps_url character varying,
    verified boolean DEFAULT false,
    story text,
    specialty character varying,
    mission character varying
);

ALTER TABLE public.cafes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cafes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.friend_requests (
    id uuid DEFAULT extensions.uuid_generate_v4() NOT NULL,
    sender_id uuid NOT NULL,
    receiver_id uuid NOT NULL,
    status public.friend_request_status DEFAULT 'pending'::public.friend_request_status NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    token uuid DEFAULT extensions.uuid_generate_v4()
);

CREATE TABLE public.friendships (
    id uuid DEFAULT extensions.uuid_generate_v4() NOT NULL,
    user1_id uuid NOT NULL,
    user2_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.invitations (
    id uuid DEFAULT extensions.uuid_generate_v4() NOT NULL,
    inviter_id uuid NOT NULL,
    invitee_id uuid,
    meetup_date timestamp with time zone NOT NULL,
    status public.invitation_status DEFAULT 'pending'::public.invitation_status NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    token uuid DEFAULT extensions.uuid_generate_v4(),
    cafe_id bigint
);

CREATE TABLE public.profile_badges (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    profile_id uuid NOT NULL,
    badge_id character varying NOT NULL
);

ALTER TABLE public.profile_badges ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.profile_badges_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.profiles (
    id uuid NOT NULL,
    updated_at timestamp with time zone,
    username text,
    full_name text,
    avatar_url text,
    website text,
    "firstName" character varying,
    "lastName" character varying,
    email character varying,
    wants_reminders boolean,
    wants_notifications boolean,
    last_seen_at timestamp with time zone,
    preferred_language character varying,
    cafe_preferences jsonb,
    is_beta_user boolean,
    preferences jsonb,
    CONSTRAINT username_length CHECK ((char_length(username) >= 3))
);

CREATE VIEW public.random_coffee_shops AS
 SELECT id,
    name,
    address,
    city
   FROM public.cafes
  ORDER BY (random())
 LIMIT 5;
