-- Part 3b: Additional Tables

CREATE TABLE public.friend_invites (
    id uuid DEFAULT extensions.uuid_generate_v4() NOT NULL,
    inviter_id uuid NOT NULL,
    invitee_email character varying NOT NULL,
    token character varying NOT NULL,
    accepted boolean DEFAULT false NOT NULL,
    accepted_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.communities (
    id uuid DEFAULT extensions.uuid_generate_v4() NOT NULL,
    name character varying NOT NULL,
    description text,
    created_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.community_members (
    id uuid DEFAULT extensions.uuid_generate_v4() NOT NULL,
    community_id uuid NOT NULL,
    user_id uuid NOT NULL,
    role character varying,
    joined_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.events (
    id uuid DEFAULT extensions.uuid_generate_v4() NOT NULL,
    community_id uuid,
    created_by uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    date timestamp with time zone NOT NULL,
    name character varying NOT NULL,
    description text,
    location character varying
);

CREATE TABLE public.event_participants (
    id uuid DEFAULT extensions.uuid_generate_v4() NOT NULL,
    event_id uuid NOT NULL,
    user_id uuid NOT NULL,
    role character varying,
    joined_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.friendship_audit (
    id uuid DEFAULT extensions.uuid_generate_v4() NOT NULL,
    action character varying NOT NULL,
    actor_id uuid,
    target_user uuid,
    occurring_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.user_badges (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    badge_key character varying NOT NULL,
    awarded_at timestamp with time zone
);

ALTER TABLE public.user_badges ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_badges_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Cities table for meetups and analytics
CREATE TABLE public.cities (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  country text
);
